### ISSUE TITLE
Community guideline suggestions

### ISSUE THREAD

**Issue by j6626** [richteague/disksurf#3]
If you are interested in contributing, please submit a pull request. New functions should be documented in a manner consistent with existing code. Software bugs or mistakes in the documentation should be reported by opening up an issue. If reporting a software bug, please provide a minimal reproducible example. If your bug is triggered with a proprietary image cube,

**Comment by richteague** [comment]
Did you miss the final part of this?

**Comment by j6626** [comment]
argh, thought I deleted that last fragment. I figured a decent number of people using this package might have proprietary data that they don't want to share, so I I figured they should still raise the issue on Github (so that other people can see if they have similar issues), but request to share the data itself privately with you?

**Comment by richteague** [comment]
I think we can leave that bit out and if folks have an issue then we talk with them directly.
