### ISSUE TITLE
__future__ in detect_peaks

### ISSUE THREAD

**Issue by emptymalei** [richteague/disksurf#4]
Thanks for the nice package. 🎉 

I am wondering if the following imports are really needed, as this package already requires python 3. 🤔 

https://github.com/richteague/disksurf/blob/8b1fdf1c1780eefa6c6d008ca4a6739a5a1f45df/disksurf/detect_peaks.py#L30

(https://github.com/openjournals/joss-reviews/issues/3827)

**Comment by richteague** [comment]
Good catch, I've removed this with https://github.com/richteague/disksurf/commit/451923a1d2dce9fb51f57fdf4696b2b5120cdb6e.
